import {  Table } from "react-bootstrap";

const ScraperTable = () => {
    return (
      
    <div responsive="true">
      <Table striped bordered>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Number</th>
            <th>Location</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
          <tr>
            <td>Akeem</td>
            <td>Akeem@gmail.com</td>
            <td>09056490101</td>
            <td>Nigeria</td>
          </tr>
        </tbody>
      </Table>
    </div>
  );
};

export default ScraperTable;
